### ISSUE TITLE
using with PHPUnit

### ISSUE THREAD

**Issue by RusAlex** [php-deal/framework#7] opened 2015-11-23 10:47 UTC
Met a Fatal Error:

``` bash
PHP Fatal error:  Cannot redeclare class PHP_TokenWithScope in /usr/share/nginx/yii-version/vendor/phpunit/php-token-stream/src/Token.php on line 171
```

Using Contracts with a PHPUnit

**Comment by lisachenko** [comment] 2015-11-24 10:17
Hello, sorry for the late response!

Could you please add a `debug_print_backtrace()` at the beginning of `yii-version/vendor/phpunit/php-token-stream/src/Token.php` file. This will show traces, how this file is included for several times.

**Comment by RusAlex** [comment] 2015-11-25 21:14
#0  include() called at
 [/usr/share/nginx/yii-version/vendor/lisachenko/go-aop-php/src/Instrument/ClassLoading/AopComposerLoader.php:97]
 #1
 Go\Instrument\ClassLoading\AopComposerLoader->loadClass(PHP_Token)
 #2  spl_autoload_call(PHP_Token)
 #3  class_exists(PHP_Token) called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/Util/Blacklist.php:90]
 #4  PHPUnit_Util_Blacklist->initialize() called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/Util/Blacklist.php:58]
 #5  PHPUnit_Util_Blacklist->getBlacklistedDirectories() called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:1003]
 #6  PHPUnit_TextUI_TestRunner->getCodeCoverageFilter() called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:63]
 #7  PHPUnit_TextUI_TestRunner->__construct() called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/TextUI/Command.php:175]
 #8  PHPUnit_TextUI_Command->createRunner() called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/TextUI/Command.php:111]
 #9  PHPUnit_TextUI_Command->run(Array ([0] => vendor/bin/phpunit,[1]
 => --exclude-group,[2] => site,[3] => -c,[4] =>
 www/protected/tests/phpunit.xml,[5] => --stop-on-failure,[6] =>
 www/protected/tests/unit/), 1) called at
 [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/src/TextUI/Command.php:99]
 #10 PHPUnit_TextUI_Command::main() called at [/usr/share/nginx/yii-version/vendor/phpunit/phpunit/phpunit:36]

**Comment by lisachenko** [comment] 2015-11-26 15:24
And where is the second trace? I'm expecting exactly two traces for that fatal error. First trace shouldn't produce an error, and the second one will cause a fatal error. 

Now it looks like this call is second, eg, phpunit already have loaded all files and them one more `require` was called with AOP, causing a fatal error.

**Comment by gambledor** [comment] 2015-12-11 11:33
I've got the same issue.

**Comment by lisachenko** [comment] 2015-12-16 10:02
Related to the https://github.com/goaop/framework/issues/239

**Comment by icanhazstring** [comment] 2017-12-23 15:57
After testing I could not reproduce this with the latest version of goaop/framework.

So I will close this for now. @RusAlex if updating to the latest version does not fix you problem, feel free to reopen the issue and add more details on how to reproduce this.

**Closed by icanhazstring** 2017-12-23 15:57 UTC
Labels: question
